name: Add new issues to the project

on:
  issues:
    types: [opened]

secrets:
  GH_PAT_ADD_ISSUES_TO_PROJECT:
    required: true

jobs:
  add_issue_to_project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:

      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: "https://github.com/users/bak0al3x/projects/2"
          github-token: ${{ secrets.GH_PAT_ADD_ISSUES_TO_PROJECT }}
          labeled: feature, bug, enhancement
          label-operator: OR